language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

dist: trusty
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
  - php: 5.3
    dist: precise
  - php: 7.1
    env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - composer install --dev

script:
  - if [ $DEFAULT = '1' ]; then vendor/bin/phpunit --exclude-group deprecated --stderr; fi
  - if [ $CODECOVERAGE = '1' ]; then vendor/bin/phpunit --exclude-group deprecated --stderr --coverage-clover=coverage.xml; fi

after_success:
  - if [[ $CODECOVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
